ToTheMoon/ToTheMoon/Models/SpaceViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ToTheMoon.Models
{
    public class SpaceUpdateCapacityViewModel
    {
        public int SpaceID { get; set; }

        public string Name { get; set; }

        [Display(Name = "New Capacity (GB)")]
        public int capacity { get; set; }

        [Display(Name = "New Used Space (GB)")]
        public int used { get; set; }
    }
}

ToTheMoon/ToTheMoon/Controllers/IncreaseSpaceRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ToTheMoon.Models;
using ToTheMoon.DAL;

namespace ToTheMoon.Controllers
{
    public class IncreaseSpaceRequestController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: /IncreaseSpaceRequest/
        public ActionResult Index()
        {
            return View(db.IncreaseSpaceRequests.ToList());
        }

        public ActionResult Review(int? id)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            ViewBag.UserRole = currentUser.role;

            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("../Dashboard");
            }

            IncreaseSpaceRequest incspacerequest = db.IncreaseSpaceRequests.Find(id);

            if (incspacerequest == null)
            {
                return RedirectToAction("../Dashboard");
            }

            incspacerequest.requester = (ApplicationUser)db.Users.Find(incspacerequest.requester_key);
            incspacerequest.space = db.Spaces.Find(incspacerequest.SpaceID);
            return View(incspacerequest);
        }


        // GET: /IncreaseSpaceRequest/Create/<id>
        public ActionResult Create(int? ID)
        {
            if (ID == null)
            {
                return RedirectToAction("../Dashboard");
            }
            IncreaseSpaceRequest increasespacerequest = new IncreaseSpaceRequest();
            increasespacerequest.space = db.Spaces.Find(ID);
            increasespacerequest.SpaceID = (int)ID;
            if(increasespacerequest.space == null)
            {
                return RedirectToAction("../Dashboard");
            }
            return View(increasespacerequest);
        }

        // POST: /IncreaseSpaceRequest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,SpaceID,brief,increase")] IncreaseSpaceRequest increasespacerequest)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());
            increasespacerequest.space = db.Spaces.Find(increasespacerequest.SpaceID);
            increasespacerequest.requester = (ApplicationUser)db.Users.Find(currentUser.Id);
            increasespacerequest.requester_key = currentUser.Id;



            increasespacerequest.timestamp = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.IncreaseSpaceRequests.Add(increasespacerequest);
                db.SaveChanges();
                return RedirectToAction("../Dashboard");
            }

            return View(increasespacerequest);
        }

       /* // GET: /IncreaseSpaceRequest/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncreaseSpaceRequest increasespacerequest = db.IncreaseSpaceRequests.Find(id);
            if (increasespacerequest == null)
            {
                return HttpNotFound();
            }
            return View(increasespacerequest);
        }*/

        // POST: /IncreaseSpaceRequest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Review")]
        [ValidateAntiForgeryToken]
        public ActionResult Review([Bind(Include = "ID,SpaceID,brief,increase")] IncreaseSpaceRequest increasespacerequest)
        {
            IncreaseSpaceRequest isr = db.IncreaseSpaceRequests.Find(increasespacerequest.ID);
            isr.brief = increasespacerequest.brief;
            isr.space = db.Spaces.Find(increasespacerequest.SpaceID);

            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            if (ModelState.IsValid && currentUser.role != GlobalRole.REGULAR)
            {
                isr.timestamp = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("../Dashboard");
            }
            return View(increasespacerequest);
        }

        // GET: /IncreaseSpaceRequest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("../Dashboard");
            }
            IncreaseSpaceRequest increasespacerequest = db.IncreaseSpaceRequests.Find(id);
            if (increasespacerequest == null)
            {
                return RedirectToAction("../Dashboard");
            }
            return View(increasespacerequest);
        }

        //[HttpPost, ActionName("Approve")]
        //[ValidateAntiForgeryToken]
        public ActionResult Approve(int id)
        {
            IncreaseSpaceRequest incspacerequest = db.IncreaseSpaceRequests.Find(id);
            Space space = db.Spaces.Find(incspacerequest.SpaceID);

            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());
            if (currentUser.role != GlobalRole.REGULAR)
            {
                if(((Int64)space.capacity + (Int64)incspacerequest.increase) > int.MaxValue)
                {
                    space.capacity = int.MaxValue;
                }
                else
                {
                    space.capacity += incspacerequest.increase;
                }


                db.IncreaseSpaceRequests.Remove(incspacerequest);
                db.SaveChanges();

                ///////////////////////////////
                ///////////////////////////////
                ////Send Email to Requester////
                ///////////////////////////////
                ///////////////////////////////

            }



            return RedirectToAction("../Dashboard");
        }

        // POST: /incspacerequest/Delete/5
        //[HttpPost, ActionName("Decline")]
        //[ValidateAntiForgeryToken]
        public ActionResult Decline(int id)
        {
            IncreaseSpaceRequest incspacerequest = db.IncreaseSpaceRequests.Find(id);

            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            if(currentUser.role != GlobalRole.REGULAR)
            {
                db.IncreaseSpaceRequests.Remove(incspacerequest);
                db.SaveChanges();

                ///////////////////////////////
                ///////////////////////////////
                ////Send Email to Requester////
                ///////////////////////////////
                ///////////////////////////////
            }

            return RedirectToAction("../Dashboard");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToTheMoon/ToTheMoon/Controllers/SpacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToTheMoon.Models;
using ToTheMoon.DAL;

namespace ToTheMoon.Controllers
{
    public class SpacesController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: /Spaces/
        public ActionResult Index()
        {
            return View(db.Spaces.ToList());
        }

        // GET: /Spaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            return View(space);
        }

        // GET: /Spaces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Spaces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,SpaceName,Description,SpaceTotal,SpaceUsed")] Space space)
        {
            if (ModelState.IsValid)
            {
                db.Spaces.Add(space);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(space);
        }

        // GET: /Spaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            return View(space);
        }

        // POST: /Spaces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,SpaceName,Description,SpaceTotal,SpaceUsed")] Space space)
        {
            if (ModelState.IsValid)
            {
                db.Entry(space).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(space);
        }

        // GET: /Spaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            return View(space);
        }

        // POST: /Spaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Space space = db.Spaces.Find(id);
            db.Spaces.Remove(space);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToTheMoon/ToTheMoon/Controllers/UserSpaceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ToTheMoon.Models;
using ToTheMoon.DAL;

namespace ToTheMoon.Controllers
{
    public class UserSpaceController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: /UserSpace/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("../Dashboard");
            }
            UserSpace userspace = db.UserSpaces.Find(id);
            
            if (userspace == null)
            {
                //return HttpNotFound();
                return RedirectToAction("../Dashboard");
            }

            userspace.user = (ApplicationUser)db.Users.Find(userspace.userKey);

            return View(userspace);
        }

        // POST: /UserSpace/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ProductId,role")] UserSpace userspace)
        {
            SpaceRole role = userspace.role;

            userspace = db.UserSpaces.Find(userspace.ProductId);

            if (ModelState.IsValid && userspace.userKey != userspace.space.PIKey)
            {
                userspace.role = role;

                //////////////////////////
                //////////////////////////
                ////Send Email to User////
                //////////////////////////
                //////////////////////////

                db.Entry(userspace).State = EntityState.Modified;
                db.SaveChanges();


                return RedirectToAction("../Space/Review/" + userspace.space.key);
            }
            return View(userspace);
        }

        // GET: /UserSpace/Create/5
        public ActionResult Create(int? id)
        {
            if(id == null)
            {
                return Redirect("../Dashboard");
            }
            Space space = db.Spaces.Find(id);
            List<ApplicationUser> alreadyUsers = db.UserSpaces.ToList().FindAll(us => us.spaceKey.Equals(id)).Select(s => s.user).ToList();
            alreadyUsers.Add(space.PI);
            ViewBag.Users = db.Users.ToList().Except(alreadyUsers);

            if(space == null)
            {
                return Redirect("../Dashboard");
            }
            UserSpace userspace = new UserSpace();
            userspace.space = db.Spaces.Find(id);
            userspace.spaceKey = userspace.space.key;
            return View(userspace);
        }

        // POST: /UserSpace/Create/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "spaceKey,role,userKey")] UserSpace userspace)
        {
            userspace.user = (ApplicationUser)db.Users.Find(userspace.userKey);
            userspace.space = db.Spaces.Find(userspace.spaceKey);
            if (ModelState.IsValid && userspace.user != null)
            {

                //////////////////////////
                //////////////////////////
                ////Send Email to User////
                //////////////////////////
                //////////////////////////

                db.UserSpaces.Add(userspace);
                db.SaveChanges();

                return RedirectToAction("Review","Space",new {id = userspace.space.key});
            }
            Space space = db.Spaces.Find(userspace.spaceKey);
            List<ApplicationUser> alreadyUsers = db.UserSpaces.ToList().FindAll(us => us.spaceKey.Equals(userspace.spaceKey)).Select(s => s.user).ToList();
            alreadyUsers.Add(space.PI);
            ViewBag.Users = db.Users.ToList().Except(alreadyUsers);
            return View(userspace);//RedirectToAction("Create", new { id = userspace.spaceKey});
        }

        // POST: /UserSpace/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            UserSpace userspace = db.UserSpaces.Find(id);
            int space_id = userspace.space.key;
            if (userspace.userKey != userspace.space.PIKey)
            {

                //////////////////////////
                //////////////////////////
                ////Send Email to User////
                //////////////////////////
                //////////////////////////

                db.UserSpaces.Remove(userspace);
                db.SaveChanges();
            }
            return RedirectToAction("Review", "Space", new { id = space_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToTheMoon/ToTheMoon/Views/Space/ChangeCapacity.cshtml
@model ToTheMoon.Models.SpaceUpdateCapacityViewModel

@{
    ViewBag.Title = "Change Capacity";
}

<h2><b>Change Capacity of</b> Space</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@(Model.Name)</h4>
        <hr />
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.SpaceID)

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.capacity, new { @class = "form-control" }) 
                @Html.ValidationMessageFor(model => model.capacity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.used, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.used, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.used)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Dashboard", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheMoon/ToTheMoon/Views/Space/Edit.cshtml
@model ToTheMoon.Models.Space

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Space</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.key)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacity)
                @Html.ValidationMessageFor(model => model.capacity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.used, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.used)
                @Html.ValidationMessageFor(model => model.used)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.increase, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.increase)
                @Html.ValidationMessageFor(model => model.increase)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIKey, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIKey)
                @Html.ValidationMessageFor(model => model.PIKey)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheMoon/ToTheMoon/Views/Space/Review.cshtml
@model ToTheMoon.Models.Space
@using ToTheMoon.Models

@{
    ViewBag.Title = "Review Space";
}

<h2><b>Review</b> Space</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.Name)</h4>
        @Html.HiddenFor(model => model.Name)
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.key)

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, new { @class = "col-md-2 control-label" })
            <div class="col-md-4">
                <p class="form-control-static">
                    @Html.DisplayFor(model => model.capacity) GB

                    @{if (ViewBag.canChangeCapacity)
                    {
                        @(" | ")
                        @Html.ActionLink("Add more", "ChangeCapacity", "Space", new { ID = Model.key }, null)
                    }
                    else if (ViewBag.canRequestSpace)
                    {
                        @(" | ")
                        @Html.ActionLink("Request more", "Create", "IncreaseSpaceRequest", new { ID = Model.key }, null)
                    }
                    }
                </p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.used, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control-static">
                    @Html.DisplayFor(model => model.used) GB
                    @{if (ViewBag.canChangeCapacity)
                    {
                        @(" | ")
                        @Html.ActionLink("Manual change", "ChangeCapacity", "Space", new { ID = Model.key }, null)
                    }           
                    }     
                </p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.increase, new { @class = "col-md-2 control-label" })
            <div class="col-md-4">
                <p class="form-control-static">
                    @Html.DisplayFor(model => model.increase) GB
                </p>
            </div>
            <div class="col-md-6">
                <p class="form-control-static">
                    @Html.ValidationMessageFor(model => model.increase)
                </p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PI, new { @class = "col-md-2 control-label" })
            <div class="col-md-4">
                @if (ViewBag.canChangePI == true)
                {
                    List<SelectListItem> userList = new List<SelectListItem>();
                    foreach (ApplicationUser user in ViewBag.dataManagerUsers)
                    {
                        SelectListItem i = new SelectListItem();
                        i.Text = user.FirstName + " " + user.LastName;
                        i.Value = user.Id;
                        userList.Add(i);
                    }
                    @Html.DropDownListFor(model => model.PIKey, new SelectList(userList, "Value", "Text"), new { @class = "form-control" })
                }
                else
                {
                    <p class="form-control-static">
                        @Html.DisplayFor(model => model.PI.FirstName)
                        @(" ")
                        @Html.DisplayFor(model => model.PI.LastName)
                    </p>
                }
            </div>
            <div class="col-md-6">
                <p class="form-control-static">
                    @Html.ValidationMessageFor(model => model.increase)
                </p>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Data Managers", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control-static">
                    @{foreach (UserSpace sp in ViewBag.dataManagers)
                    {
                        @String.Join(" ", sp.user.FirstName, sp.user.LastName)
                        if (!sp.space.PIKey.Equals(sp.userKey) && ViewBag.canChangeRoles)
                        {
                            @(" | ")
                            @Html.ActionLink("Edit", "Edit", "UserSpace", new { @ID = sp.ProductId }, null);
                            @(" | ")
                            @Html.ActionLink("Remove", "Delete", "UserSpace", new { @ID = sp.ProductId }, null);
                        }

                        <br />
                    }
                    }

                    @if (ViewBag.canAddUsers)
                    {
                        @Html.ActionLink("Add More", "Create", "UserSpace", new { ID = Model.key }, null)                        
                    }
                </p>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Read/Write Researchers", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control-static">
                    @{foreach (UserSpace sp in ViewBag.readWriteResearchers)
                    {
                        @String.Join(" ", sp.user.FirstName, sp.user.LastName);
                        if (ViewBag.canChangeRoles)
                        {
                            @(" | ")
                            @Html.ActionLink("Edit", "Edit", "UserSpace", new { @ID = sp.ProductId }, null);
                            @(" | ")
                            @Html.ActionLink("Remove", "Delete", "UserSpace", new { @ID = sp.ProductId }, null);
                        }

                        <br />
                    }
                    }

                    @if (ViewBag.canAddUsers)
                    {
                        @Html.ActionLink("Add More", "Create", "UserSpace", new { ID = Model.key }, null)                        
                    }
                </p>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Read-Only Researchers", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control-static">
                    @{foreach (UserSpace sp in ViewBag.readOnlyResearchers)
                    {
                        @String.Join(" ", sp.user.FirstName, sp.user.LastName);
                        if (ViewBag.canChangeRoles)
                        {
                            @(" | ")
                            @Html.ActionLink("Edit", "Edit", "UserSpace", new { @ID = sp.ProductId }, null);
                            @(" | ")
                            @Html.ActionLink("Remove", "Delete", "UserSpace", new { @ID = sp.ProductId }, null);
                        }
                        
                        <br />
                    }
                    }

                    @if (ViewBag.canAddUsers)
                    {
                        @Html.ActionLink("Add More", "Create", "UserSpace", new { ID = Model.key }, null)                        
                    }
                </p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br />
<div>
    @Html.ActionLink("Back to Dashboard", "Dashboard", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}