ToTheMoon/ToTheMoon/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ToTheMoon.Models;
using ToTheMoon.DAL;

namespace ToTheMoon.Controllers
{
    public class HomeController : Controller
    {
        private ProjectContext db = new ProjectContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return Redirect("Dashboard");
            }

            return View();
        }

        [Route("Dashboard")]
        public ActionResult Dashboard()
        {

            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            if (currentUser == null)
            {
                return Redirect("/");
            }

            ViewBag.UserRole = currentUser.role;

            if(currentUser.role == GlobalRole.ADMIN)
            {
                ViewBag.NewSpaceRequests = db.NewSpaceRequests.ToList<NewSpaceRequest>();
                ViewBag.IncreaseSpaceRequests = db.IncreaseSpaceRequests.ToList<IncreaseSpaceRequest>();
                ViewBag.Spaces = db.Spaces.ToList<Space>();
            }
            else if (currentUser.role == GlobalRole.APPROVER)
            {

                ViewBag.NewSpaceRequests = db.NewSpaceRequests.ToList<NewSpaceRequest>().FindAll(nsr => manager.FindById(nsr.requester_key).faculty.Equals(currentUser.faculty));
                ViewBag.IncreaseSpaceRequests = db.IncreaseSpaceRequests.ToList<IncreaseSpaceRequest>().FindAll(isr => manager.FindById(isr.requester_key).faculty.Equals(currentUser.faculty));
                ViewBag.Spaces = db.Spaces.ToList<Space>().FindAll(s => s.PI.faculty.Equals(currentUser.faculty));
                ViewBag.Faculty = currentUser.faculty;
            }
            else
            {
                //change this to only show the right things
                ViewBag.NewSpaceRequests = db.NewSpaceRequests.ToList<NewSpaceRequest>().FindAll(nsr => nsr.requester_key.Equals(currentUser.Id));
                ViewBag.IncreaseSpaceRequests = db.IncreaseSpaceRequests.ToList<IncreaseSpaceRequest>().FindAll(isr => isr.requester_key.Equals(currentUser.Id));
                ViewBag.UserSpaces = db.UserSpaces.ToList<UserSpace>().FindAll(us => us.user.UserName.Equals(currentUser.UserName));
            }
            return View();
        }
    }
}

ToTheMoon/ToTheMoon/Controllers/NewSpaceRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ToTheMoon.Models;
using ToTheMoon.DAL;

namespace ToTheMoon.Controllers
{
    public class NewSpaceRequestController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: /NewSpaceRequest/
        public ActionResult Index()
        {
            return View(db.NewSpaceRequests.ToList());
        }

        // GET: /NewSpaceRequest/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //       return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //   }
        //    NewSpaceRequest newspacerequest = db.NewSpaceRequests.Find(id);
        //    if (newspacerequest == null)
        //   {
        //        return HttpNotFound();
        //    }
        //    return View(newspacerequest);
        //}

        // GET: /NewSpaceRequest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /NewSpaceRequest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="name,brief,SpaceID,capacity,increase")] NewSpaceRequest newspacerequest)
        {

            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            newspacerequest.requester = (ApplicationUser)db.Users.Find(currentUser.Id);
            newspacerequest.requester_key = currentUser.Id;

            newspacerequest.timestamp = DateTime.Now;
    
            if (ModelState.IsValid)
            {
                db.NewSpaceRequests.Add(newspacerequest);
                db.SaveChanges();
                return RedirectToAction("../Dashboard");
            }

            return View(newspacerequest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Review([Bind(Include = "ID,comment")] NewSpaceRequestCommentViewModel nsrViewModel)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            if (currentUser.role != GlobalRole.ADMIN)
            {
                return RedirectToAction("Review", "Space", new { ID = nsrViewModel.ID });
            }

            if (ModelState.IsValid)
            {
                NewSpaceRequest nsr = db.NewSpaceRequests.Find(nsrViewModel.ID);
                nsr.comment = nsrViewModel.comment;
                nsr.timestamp = DateTime.Now;

                ///////////////////////////////
                ///////////////////////////////
                ////Send Email to Requester////
                ///////////////////////////////
                ///////////////////////////////

                db.Entry(nsr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Dashboard", "Home");
            }

            return View(nsrViewModel);
        }

        public ActionResult Review(int? id)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            ViewBag.UserRole = currentUser.role;

            if (id == null)
            {
                return RedirectToAction("Dashboard", "Home");
            }

            NewSpaceRequest newspacerequest = db.NewSpaceRequests.Find(id);

            if (newspacerequest == null && (currentUser.role != GlobalRole.REGULAR || currentUser.Id == newspacerequest.requester_key))
            {
                return RedirectToAction("Dashboard", "Home");
            }

            if (currentUser.role != GlobalRole.REGULAR)
            {
                ViewBag.canComment = false;
            }
            else
            {
                ViewBag.canComment = true;
            }

            NewSpaceRequestCommentViewModel nsrViewModel = new NewSpaceRequestCommentViewModel();
            nsrViewModel.ID = newspacerequest.ID;
            nsrViewModel.name = newspacerequest.name;
            nsrViewModel.brief = newspacerequest.brief;
            nsrViewModel.capacity = newspacerequest.capacity;
            nsrViewModel.increase = newspacerequest.increase;
            nsrViewModel.requester = manager.FindById(newspacerequest.requester_key);
            nsrViewModel.comment = newspacerequest.comment;

            return View(nsrViewModel);
        }

        // POST: /NewSpaceRequest/Delete/5
        //[HttpPost, ActionName("Review")]
        //[ValidateAntiForgeryToken]
        public ActionResult Approve(int id)
        {
            if (ViewBag.UserRole != GlobalRole.REGULAR)
            {
                NewSpaceRequest newspacerequest = (NewSpaceRequest)db.NewSpaceRequests.Find(id);
                Space space = new Space();
                space.capacity = newspacerequest.capacity;
                space.increase = newspacerequest.increase;
                space.key = newspacerequest.SpaceID;
                space.Name = newspacerequest.name;
                space.PI = (ApplicationUser)db.Users.Find(newspacerequest.requester_key);
                space.PIKey = newspacerequest.requester_key;
                
                //make our progress bars look pretty
                Random random = new Random();
                space.used = random.Next(0, space.capacity);

                UserSpace userspace = new UserSpace();
                userspace.space = space;
                userspace.user = (ApplicationUser)db.Users.Find(newspacerequest.requester_key);
                userspace.userKey = newspacerequest.requester_key;

                userspace.role = SpaceRole.DATAMANAGER;

                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
                ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());
                if (currentUser.role != GlobalRole.REGULAR)
                {

                    db.Spaces.Add(space);
                    db.UserSpaces.Add(userspace);
                    db.NewSpaceRequests.Remove(newspacerequest);
                    db.SaveChanges();

                    ///////////////////////////////
                    ///////////////////////////////
                    ////Send Email to Requester////
                    ///////////////////////////////
                    ///////////////////////////////

                }

            }


            return RedirectToAction("../Dashboard");
        }

        // POST: /NewSpaceRequest/Delete/5
        //[HttpPost, ActionName("Review")]
        //[ValidateAntiForgeryToken]
        public ActionResult Decline(int id)
        {
            NewSpaceRequest newspacerequest = db.NewSpaceRequests.Find(id);
           
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ProjectContext()));
            ApplicationUser currentUser = manager.FindById(User.Identity.GetUserId());

            if(currentUser.role != GlobalRole.REGULAR)
            {

                db.NewSpaceRequests.Remove(newspacerequest);
                db.SaveChanges();

                ///////////////////////////////
                ///////////////////////////////
                ////Send Email to Requester////
                ///////////////////////////////
                ///////////////////////////////

            }

            return RedirectToAction("../Dashboard");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToTheMoon/ToTheMoon/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToTheMoon.Models;
using ToTheMoon.DAL;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ToTheMoon.Controllers
{
    public class RequestController : Controller
    {
        private static ProjectContext db = new ProjectContext();
        private static UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

        // GET: /Request/
        public ActionResult Index()
        {
            return View(db.Requests.ToList());
        }

        // GET: /Request/Details/<id>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request req = db.Requests.Find(id);
            if (req == null)
            {
                return HttpNotFound();
            }
            return View(req);
        }

        // GET: /Request/Space
        public ActionResult Space()
        {
            return View("Space");
        }

        // POST: /Request/Space
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Space([Bind(Include = "RequestID,SpaceName,ProjectID,Description,StorageTotal,YearlyGrowth")] NewSpaceRequest newspacerequest)
        {
            if (ModelState.IsValid)
            {
                // newspacerequest.RequestTimestamp = DateTime.UtcNow;
                newspacerequest.StorageUsed = 0;
                newspacerequest.Requester = UserManager.FindById<ApplicationUser>(User.Identity.GetUserId());
                newspacerequest.RequestTimestamp = DateTime.Now;
                db.NewSpaceRequests.Add(newspacerequest);
                db.SaveChanges();
                return RedirectToAction("Dashboard", "Home");
            }

            return View(newspacerequest);
        }

        // GET: /Request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request req = db.Requests.Find(id);
            if (req == null)
            {
                return HttpNotFound();
            }
            return View(req);
        }

        // POST: /Request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Request req = db.Requests.Find(id);
            db.Requests.Remove(req);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

ToTheMoon/ToTheMoon/Views/Home/Dashboard.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using ToTheMoon.Models;

@{
    ViewBag.Title = "Dashboard";
}

<h2>Dashboard</h2>

<div class="row">
    <div class="col-md-12">
        @Html.Partial("_SpacesPartial")
    </div>
</div>
<div class="row">
    @{
        //Only bother to show Requests for Increased Space if user actually has the ability to make one
        bool DM = false;
        
        if (ViewBag.UserSpaces != null)
        {
            foreach (UserSpace us in ViewBag.UserSpaces)
            {
                if (us.role == SpaceRole.DATAMANAGER)
                {
                    DM = true;
                    break; //NOT EVEN ONCE
                }
            }
        }
        
        //make div col-md-12 if a regular user
        string RequestWidth = "col-md-12";
   
        if (ViewBag.UserRole != GlobalRole.REGULAR || DM)
        {
            RequestWidth = "col-md-6";
        }
    }
    <div class="@RequestWidth">
        @Html.Partial("_NewSpaceRequestsPartial")
    </div>
    @if (ViewBag.UserRole != GlobalRole.REGULAR || DM)
    { 
    <div class="col-md-6">
        @Html.Partial("_IncreaseSpaceRequestsPartial")
    </div>    
    }
</div>

ToTheMoon/ToTheMoon/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>FreedomSpace</h1>
    <p class="lead">FreedomSpace respects your need for space.</p>
    @if (!Request.IsAuthenticated)
    {
    <p>@Html.ActionLink("Log in", "Login", "Account", null, new { @class = "btn btn-primary btn-large"})</p>
    }
</div>

<div class="row">
    
        <h2>Getting started</h2>
        <p>
            FreedomSpace is used by Curtin University to allocate space to eligible researchers to store their work.
        </p>
        <p><a class="btn btn-default" href="http://handbook.curtin.edu.au/units/45/4549.html">Learn more &raquo;</a></p>
    
<!---    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>--->
</div>

ToTheMoon/ToTheMoon/Views/Home/_IncreaseSpaceRequestsPartial.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using ToTheMoon.Models;

<table class="table table-hover" border="1">
    <thead bgcolor="#222" style="color:white">
    <tr>
    <th>Requests for Space Increase</th>
    </tr>
    </thead>
    <tbody>
        @foreach (IncreaseSpaceRequest request in ViewBag.IncreaseSpaceRequests)
        {
            <tr>
                <td>
                    <p>Request for +@(request.increase)GB for [@request.space.key] @request.space.Name</p>
                    @Html.ActionLink("[Review]", "Review", "IncreaseSpaceRequest", new { ID = request.ID }, null)
                    @{if (ViewBag.UserRole == GlobalRole.ADMIN) { 
                        @Html.ActionLink("[Approve]", "Approve", "IncreaseSpaceRequest", new { ID = request.ID }, null)
                        @Html.ActionLink("[Decline]", "Decline", "IncreaseSpaceRequest", new { ID = request.ID }, null)
                    }
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td>
                <b>Tip: </b>You can request a space increase from the details page of spaces you manage.
            </td>
        </tr>
    </tfoot>
</table>

ToTheMoon/ToTheMoon/Views/Home/_NewSpaceRequestsPartial.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using ToTheMoon.Models;

<table class="table table-hover" border="1">
    <thead bgcolor="#222" style="color:white">
        <tr>
            <th>Requests for New Space</th>
        </tr>
    </thead>
    <tbody>
        @foreach (NewSpaceRequest request in ViewBag.NewSpaceRequests)
        {
            <tr>
                <td>
                    <p>Request for [@(request.SpaceID)] @(request.name) with @(request.capacity)GB</p>
                    @Html.ActionLink("[Review]", "Review", "NewSpaceRequest", new { ID = request.ID }, null)

                    @{
                        if (ViewBag.UserRole != GlobalRole.REGULAR)
                        {
                            @Html.ActionLink("[Approve] ", "Approve", "NewSpaceRequest", new { ID = request.ID }, null)
                            @Html.ActionLink("[Decline]", "Decline", "NewSpaceRequest", new { ID = request.ID }, null)
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td>
                To request new space, go @Html.ActionLink("here", "Create", "NewSpaceRequest").
            </td>
        </tr>
    </tfoot>
</table>

ToTheMoon/ToTheMoon/Views/Home/_NotificationsPartial.cshtml
@*<table class="table table-hover" border="1" style="width:48%">
    <thead bgcolor="#222" style="color:white">
        <tr>
            <th>My Notifications</th>
        </tr>
    </thead>
    <tr>
        <td height="55">
            <a href="#111" target="_blank">
                <p>Michael `Millie' Mroz (13333337)</p>
                <p>Cardiology 420 - now the Principal Investigator</p>
            </a>
        </td>
    </tr>
</table>*@

<table class="table table-hover" border="1" style="width:48%">
    <thead bgcolor="#222" style="color:white">
        <tr>
            <th>My Notifications</th>
        </tr>
    </thead>
    <tbody>

        @foreach (ToTheMoon.Models.Notification notification in ViewBag.Notifications)
        {
            <tr>
                <td height="55">
                    <p>@notification.Title</p>
                    <p>@notification.Desc</p>
                    @*@Html.ActionLink("[Approve]", "Approve", "Request", new { request.RequestID })
                        @Html.ActionLink("[Reject]", "Reject", "Request", new { request.RequestID })
                        @Html.ActionLink("[Comment]", "Comment", "Request", new { request.RequestID })*@
                </td>            
            </tr> 
        }

    </tbody>

</table>

ToTheMoon/ToTheMoon/Views/Home/_SpacesPartial.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using ToTheMoon.Models;

<table class="table table-hover" border="1">
    <thead bgcolor="#222" style="color:white">
        <tr>
            <th>@if (ViewBag.UserRole != GlobalRole.APPROVER)
                {
@("Faculty")
            }
            else
            {@ViewBag.Faculty.ToString()}
             Storage Spaces</th>

            @if (ViewBag.UserRole == GlobalRole.REGULAR)
            {
                <th>Role</th>
            }
            
            <th colspan="1">Total Space</th>
            <th>Options</th>
        </tr>
    </thead>

    <tbody>
        @{if (ViewBag.UserRole == GlobalRole.REGULAR)
        {
            foreach (ToTheMoon.Models.UserSpace userspace in ViewBag.UserSpaces)
            {
                <tr>
                    <!-- space name -->
                    <td class="col-md-3">
                        <span>@userspace.space.Name</span>
                    </td>

                    <!-- user's space-specific permissions -->
                    <td class="col-md-2">
                    @{
                        if(userspace.space.PIKey == User.Identity.GetUserId())
                        {
                            <span>Principal Investigator</span>
                        }
                        else if(userspace.role == SpaceRole.COLLAB_RO)
                        {
                            <span>Read-Only Reasearcher</span>
                        }
                        else if(userspace.role == SpaceRole.COLLAB_RW)
                        {
                            <span>Read/Write Reasearcher</span>
                        }
                        else //SpaceRole.DATAMANAGER
                        {
                            <span>Data Manager</span>
                        }
                    }
                    </td>

                    <!-- percentage bar -->
                    <td class="col-md-6">
                        <div class="progress" style="margin-bottom: 0px">
                            @{
                        double percentageComplete = ((float)userspace.space.used / (float)userspace.space.capacity) * 100;
                        percentageComplete = Math.Round(percentageComplete, 0);
                            }
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="@userspace.space.used" aria-valuemin="0" aria-valuemax="@userspace.space.capacity" style="width: @percentageComplete%">
                                <p>@userspace.space.used GB of @userspace.space.capacity GB</p>
                            </div>
                        </div>
                    </td>

                    <!-- review link -->
                    <td class="col-md-1">
                        @Html.ActionLink("Review", "Review", "Space", new { ID = userspace.space.key }, null)
                    </td>
                </tr>
            }
        }
        else
        {
            foreach (ToTheMoon.Models.Space space in ViewBag.Spaces)
            {
                <tr>
                    <!-- space name -->
                    <td class="col-md-3">
                        <span>@space.Name</span>
                    </td>

                    <td class="col-md-8">
                            <div class="progress" style="margin-bottom: 0px">
                                @{
                double percentageComplete = ((float)space.used / (float)space.capacity) * 100;
                percentageComplete = Math.Round(percentageComplete, 0);
                                }
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="@space.used" aria-valuemin="0" aria-valuemax="@space.capacity" style="width: @percentageComplete%">
                                    <p>@space.used GB of @space.capacity GB</p>
                                </div>
                            </div>
                    </td>

                    <td class="col-md-1">
                        @Html.ActionLink("Review", "Review", "Space", new { ID = space.key }, null)
                    </td>
                </tr>
            }
        }

        }
    </tbody>
</table>